#!/usr/bin/env python3

# Copyright © 2013-2019 Jakub Wilk <jwilk@jwilk.net>

import argparse
import os
import subprocess as ipc

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('server', metavar='SERVER')
    ap.add_argument('user', metavar='USER', nargs='?')
    options = ap.parse_args()
    output = ipc.check_output(['fetchmail', '--configdump'])
    data = {}
    exec(output, data)
    data = data['fetchmailrc']
    servers = data['servers']
    for server in servers:
        if server['pollname'] != options.server:
            continue
        for user in server['users']:
            if (options.user is None) or (user['remote'] == options.user):
                print(user['password'])

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
